Repository bcgov/lucy-web, pull requests merged in 2024-01, with the labels that each got.

#1162 [FIX][LUCY-188] - Fix to Admin, allow access to INSPECT Web
  app/docker-compose.yml
  app/lucy/Dockerfile
  app/lucy/package-lock.json
  app/lucy/package.json
  app/lucy/src/app/constants/app-constants.ts
  app/lucy/src/app/services/bootstrap.service.ts
  app/lucy/src/app/services/sso.service.ts
  app/lucy/src/app/utils/helpers.ts
Labels: Docker, Frontend

#1165 [LUCY-188] FIX** modify-ocbc
  app/openshift/app.bc.yaml
Labels: Frontend

#1166 [LUCY-118] FIX** Modify Build Config
  app/openshift/app.bc.yaml
Labels: Frontend

#1170 [FEATURE][LUCY-1169] - Add BlowBy table to capture BlowBy data coming from INSPECT
  api/api_sources/schema-files/blowBy.schema.yaml
  api/api_sources/schema-migration-sql/BlowBySchema/BlowBySchema.sql
  api/api_sources/sources/database/database-schema/musselApp.schema.ts
  api/api_sources/sources/database/migrations/1703285389562-CreateBlowBy.ts
  api/api_sources/sources/database/models/blowBy.ts
  api/api_sources/sources/database/models/controllers/blowBy.controller.ts
  api/api_sources/sources/database/models/controllers/watercraftRiskAssessment.controller.ts
  api/api_sources/sources/database/models/index.ts
  api/api_sources/sources/database/models/observerWorkflow.ts
  api/api_sources/sources/server/initializers/routes.ts
  api/api_sources/sources/server/modules/blowBy/blowBy.route.ts
  api/api_sources/sources/server/modules/blowBy/index.ts
Labels: Backend

#1172 [MIGRATION][LUCY-#1171] - Add a migration to add 'e.g.' to closest_city in water_body
  api/api_sources/sources/database/migrations/1706036892274-closestCityNameChangeInWaterBody.ts
Labels: Backend

#1173 [LINT][LUCY-#1171] - Update to pascal case for linting purposes
  api/api_sources/sources/database/migrations/1706036892274-closestCityNameChangeInWaterBody.ts
Labels: Backend
